<?php

/**
 * LabelsDetailByPurchaseOrderId200ResponseDataInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */

/**
 * Ship With Walmart
 *
 * This class is auto-generated by the OpenAPI generator v7.12.0 (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace Walmart\Models\CP\US\Feeds;

use Walmart\Models\BaseModel;

/**
 * LabelsDetailByPurchaseOrderId200ResponseDataInner Class Doc Comment
 *
 * @category Class

 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */
class LabelsDetailByPurchaseOrderId200ResponseDataInner extends BaseModel
{public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'labelsDetailByPurchaseOrderId_200_response_data_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'addOns' => '\Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerAddOnsInner[]',
        'boxItems' => '\Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerBoxItemsInner[]',
        'carrierFullName' => 'string',
        'carrierName' => 'string',
        'carrierServiceType' => 'string',
        'purchaseOrderId' => 'string',
        'trackingNo' => 'string',
        'trackingUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'addOns' => null,
        'boxItems' => null,
        'carrierFullName' => null,
        'carrierName' => null,
        'carrierServiceType' => null,
        'purchaseOrderId' => null,
        'trackingNo' => null,
        'trackingUrl' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'addOns' => false,
		'boxItems' => false,
		'carrierFullName' => false,
		'carrierName' => false,
		'carrierServiceType' => false,
		'purchaseOrderId' => false,
		'trackingNo' => false,
		'trackingUrl' => false
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'addOns' => 'addOns',
        'boxItems' => 'boxItems',
        'carrierFullName' => 'carrierFullName',
        'carrierName' => 'carrierName',
        'carrierServiceType' => 'carrierServiceType',
        'purchaseOrderId' => 'purchaseOrderId',
        'trackingNo' => 'trackingNo',
        'trackingUrl' => 'trackingUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'addOns' => 'setAddOns',
        'boxItems' => 'setBoxItems',
        'carrierFullName' => 'setCarrierFullName',
        'carrierName' => 'setCarrierName',
        'carrierServiceType' => 'setCarrierServiceType',
        'purchaseOrderId' => 'setPurchaseOrderId',
        'trackingNo' => 'setTrackingNo',
        'trackingUrl' => 'setTrackingUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'addOns' => 'getAddOns',
        'boxItems' => 'getBoxItems',
        'carrierFullName' => 'getCarrierFullName',
        'carrierName' => 'getCarrierName',
        'carrierServiceType' => 'getCarrierServiceType',
        'purchaseOrderId' => 'getPurchaseOrderId',
        'trackingNo' => 'getTrackingNo',
        'trackingUrl' => 'getTrackingUrl'
    ];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('addOns', $data ?? [], null);
        $this->setIfExists('boxItems', $data ?? [], null);
        $this->setIfExists('carrierFullName', $data ?? [], null);
        $this->setIfExists('carrierName', $data ?? [], null);
        $this->setIfExists('carrierServiceType', $data ?? [], null);
        $this->setIfExists('purchaseOrderId', $data ?? [], null);
        $this->setIfExists('trackingNo', $data ?? [], null);
        $this->setIfExists('trackingUrl', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        return $invalidProperties;
    }

    /**
     * Gets addOns
     *
     * @return \Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerAddOnsInner[]|null
    
     */
    public function getAddOns()
    {
        return $this->container['addOns'];
    }

    /**
     * Sets addOns
     *
     * @param \Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerAddOnsInner[]|null $addOns addOns
     *
     * @return self
    
     */
    public function setAddOns($addOns)
    {
        if (is_null($addOns)) {
            throw new \InvalidArgumentException('non-nullable addOns cannot be null');
        }
        
        $this->container['addOns'] = $addOns;
        return $this;
    }

    /**
     * Gets boxItems
     *
     * @return \Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerBoxItemsInner[]|null
    
     */
    public function getBoxItems()
    {
        return $this->container['boxItems'];
    }

    /**
     * Sets boxItems
     *
     * @param \Walmart\Models\CP\US\Feeds\LabelsDetailByPurchaseOrderId200ResponseDataInnerBoxItemsInner[]|null $boxItems boxItems
     *
     * @return self
    
     */
    public function setBoxItems($boxItems)
    {
        if (is_null($boxItems)) {
            throw new \InvalidArgumentException('non-nullable boxItems cannot be null');
        }
        
        $this->container['boxItems'] = $boxItems;
        return $this;
    }

    /**
     * Gets carrierFullName
     *
     * @return string|null
    
     */
    public function getCarrierFullName()
    {
        return $this->container['carrierFullName'];
    }

    /**
     * Sets carrierFullName
     *
     * @param string|null $carrierFullName carrierFullName
     *
     * @return self
    
     */
    public function setCarrierFullName($carrierFullName)
    {
        if (is_null($carrierFullName)) {
            throw new \InvalidArgumentException('non-nullable carrierFullName cannot be null');
        }
        
        $this->container['carrierFullName'] = $carrierFullName;
        return $this;
    }

    /**
     * Gets carrierName
     *
     * @return string|null
    
     */
    public function getCarrierName()
    {
        return $this->container['carrierName'];
    }

    /**
     * Sets carrierName
     *
     * @param string|null $carrierName carrierName
     *
     * @return self
    
     */
    public function setCarrierName($carrierName)
    {
        if (is_null($carrierName)) {
            throw new \InvalidArgumentException('non-nullable carrierName cannot be null');
        }
        
        $this->container['carrierName'] = $carrierName;
        return $this;
    }

    /**
     * Gets carrierServiceType
     *
     * @return string|null
    
     */
    public function getCarrierServiceType()
    {
        return $this->container['carrierServiceType'];
    }

    /**
     * Sets carrierServiceType
     *
     * @param string|null $carrierServiceType carrierServiceType
     *
     * @return self
    
     */
    public function setCarrierServiceType($carrierServiceType)
    {
        if (is_null($carrierServiceType)) {
            throw new \InvalidArgumentException('non-nullable carrierServiceType cannot be null');
        }
        
        $this->container['carrierServiceType'] = $carrierServiceType;
        return $this;
    }

    /**
     * Gets purchaseOrderId
     *
     * @return string|null
    
     */
    public function getPurchaseOrderId()
    {
        return $this->container['purchaseOrderId'];
    }

    /**
     * Sets purchaseOrderId
     *
     * @param string|null $purchaseOrderId purchaseOrderId
     *
     * @return self
    
     */
    public function setPurchaseOrderId($purchaseOrderId)
    {
        if (is_null($purchaseOrderId)) {
            throw new \InvalidArgumentException('non-nullable purchaseOrderId cannot be null');
        }
        
        $this->container['purchaseOrderId'] = $purchaseOrderId;
        return $this;
    }

    /**
     * Gets trackingNo
     *
     * @return string|null
    
     */
    public function getTrackingNo()
    {
        return $this->container['trackingNo'];
    }

    /**
     * Sets trackingNo
     *
     * @param string|null $trackingNo trackingNo
     *
     * @return self
    
     */
    public function setTrackingNo($trackingNo)
    {
        if (is_null($trackingNo)) {
            throw new \InvalidArgumentException('non-nullable trackingNo cannot be null');
        }
        
        $this->container['trackingNo'] = $trackingNo;
        return $this;
    }

    /**
     * Gets trackingUrl
     *
     * @return string|null
    
     */
    public function getTrackingUrl()
    {
        return $this->container['trackingUrl'];
    }

    /**
     * Sets trackingUrl
     *
     * @param string|null $trackingUrl trackingUrl
     *
     * @return self
    
     */
    public function setTrackingUrl($trackingUrl)
    {
        if (is_null($trackingUrl)) {
            throw new \InvalidArgumentException('non-nullable trackingUrl cannot be null');
        }
        
        $this->container['trackingUrl'] = $trackingUrl;
        return $this;
    }
}
